name: 'deGov -  Simplenews - Settings'
description: 'Eintellungen f√ºr das Modul "simplenews"'
type: module
core: 8.x
dependencies:
  - degov_blogarticle
  - field
  - language
  - menu_ui
  - node
  - panelizer
  - path
  - simplenews
  - text
  - user
  - workbench_moderation
